# This role will make the targeted node ansible-ready, by:
# - configure the master node
# - install K8s on the master node

- name: network configuration of master node
  include: master_network_config.yml
  tag:
    - master_network

#- name: k8s installation on master node
#  include: master_k8s_install.yml
#  tag:
#    - master_k8s_install