# The project ansible k8s on RasPi YAML

---
- hosts: [masters]
  become: root
  #include variables here
  
  roles:
    - { role: prepare_master_role }

- hosts: [workers]
  become: root
  #include variables here

  roles:
    #- { role: prepare_workers_role }