# The project ansible k8s on RasPi YAML

---
- hosts: [cluster]
  become: root
  #include variables here
  
  roles:
    #- { role: setup_network_role }
    #- { role: prepare_cluster_role }
    - { role: install_k8s_role }
