# Playbook to add user 'ans'

- name: create user ans
  become: yes
  user:
    name: ans
    group: sudo
    password: rVp-tJa8
    state: present

- name: give ans passwordless sudo rights
  become: yes
  blockinfile:
    path: /etc/sudoers.d/ans_no_password
    create: yes
    block: |
      # User rules for admin
      admin ALL=(ALL) NOPASSWD:ALL
    state: present
